region               = "ap-south-1"
aws_vpc_cidr         = "10.0.0.0/24"
public_subnet_cidrs  = ["10.0.0.0/26", "10.0.0.64/26"]
private_subnets_cidr = ["10.0.0.128/26", "10.0.0.192/26"]
availability_zone    = ["ap-south-1a", "ap-south-1b"]
ami                  = "ami-0db56f446d44f2f09"
instance_type        = "t3.medium"
public_name          = "terraform server"
cluster_name         = "books"
cluster_version      = "1.35"
node_desired         = 4
min_size             = 3
max_size             = 6
allocated_storage    = 20
instance_class       = "db.t3.medium"
db_name              = "mydb"
db_username          = "admin"
db_password          = "Devops123"
db_identifier        = "my-rds"
engine               = "mysql"
engine_version       = "8.4.8"
node_instance_type   = ["t3.medium"]
bucketname           = "shahirmulticloud"
