apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: test
type: Opaque
data:
  db-host: bXktcmRzLmNoZ3FrNnVzNGdrOC5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t
  db-username: YWRtaW4=
  db-password: RGV2b3BzMTIz